# The label to apply to this deployment, 
# used to manage multiple instances of the same application
Instance: default

# The HTML data that nginx should serve
Data: |-
  <html>
  <body>
  <h1>Hello world!</h1>
  </body>
  </html>

# Ingress control settings  
Ingress:
  # If true, use ingress control.
  # Otherwise, generic NodePort networking will be used, 
  # and the other settings in this section will be ignored. 
  Enabled: true
  # The subdomain to associate with this service.
  # This will result in a FQDN like {subdomain}.{cluster}.slateci.net
  Subdomain: hello
  # The class of the ingress controller to use. 
  # For SLATE this should be 'slate'. 
  Class: slate

#Defines what IP ranges can access the app
#If disabled all IP addresses can access the app
NetworkPolicy:
  Enabled: false
  AllowedCIDRs: 
    - 0.0.0.0/0
### SLATE-START ###
SLATE:
  Cluster:
    DNSName: "some-cluster.slateci.net"
  Instance:
    ID: "untagged"
### SLATE-END ###
