apiVersion: v1
kind: Service
metadata:
  name: {{ template "nginx.fullname" . }}
  labels:
    app: {{ template "nginx.name" . }}
    chart: {{ template "nginx.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: {{ template "nginx.name" . }}
    instance: {{ .Values.Instance | quote }}
---
{{ if .Values.Ingress.Enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "nginx.fullname" . }}
  labels:
    app: {{ template "nginx.name" . }}
    chart: {{ template "nginx.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.Ingress.Class }}
spec:
  rules:
  - host: {{ .Values.Ingress.Subdomain }}.{{ .Values.SLATE.Cluster.DNSName }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "nginx.fullname" . }}
          servicePort: 80
  - host: {{ .Values.Ingress.Subdomain }}-2.{{ .Values.SLATE.Cluster.DNSName }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "nginx.fullname" . }}
          servicePort: 80
{{ end }}
