apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open-ondemand.fullname" . }}-desktop-host
data:

  {{ range .Values.clusters }}
  {{ if eq .cluster.desktopEnable true }}
  desktop-{{ .cluster.name | lower | nospace }}.yml: |
    ---
    title: {{ .cluster.name | lower | nospace }}-desktop
    cluster: {{ .cluster.name | lower | nospace | quote }}
    submit: "linux_host"
    form:
      - desktop
      - bc_num_hours
    attributes:
      bc_queue: null
      bc_account: null
      bc_num_slots: 1
      num_cores: none
  {{ end }}
  {{ end }}
