apiVersion: v1
kind: PersistentVolume
metadata:
  name: ood-pv-nfs
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.advanced.ip_addr }}
    path: {{ .Values.advanced.nfs_path | quote }}