apiVersion: v1
kind: PersistentVolume
metadata:
  name: ood-nfs-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 127.0.0.1
    path: {{ .Values.advanced.fileSharing.mountPoint | quote }}