apiVersion: v1
kind: ConfigMap
metadata:       # Primary OnDemand portal configuration file
  name: {{ include "open-ondemand.fullname" . }}-ood-portal
data:
  ood_portal.yml: |
    # /etc/ood/config/ood_portal.yml
    ---
        # List of Apache authentication directives
        # NB: Be sure the appropriate Apache module is installed for this
        # Default: (see below, uses basic auth with an htpasswd file)
        auth:
          - 'AuthType openid-connect'
          - 'Require valid-user'
    
        # Redirect user to the following URI when accessing logout URI
        # Example:
        #     logout_redirect: '/oidc?logout=https%3A%2F%2Fwww.example.com'
        # Default: '/pun/sys/dashboard/logout' (the Dashboard app provides a simple
        # HTML page explaining logout to the user)
        logout_redirect: '/oidc?logout=https%3A%2F%2F{{ .Values.Instance }}.ondemand.{{ .Values.SLATE.Cluster.DNSName }}'
    
        # Sub-uri used by mod_auth_openidc for authentication
        # Example:
        #     oidc_uri: '/oidc'
        # Default: null (disable OpenID Connect support)
        oidc_uri: '/oidc'
    
        # Set up user mapping
        user_map_match: '^([^@]+)$'

        # Host regex
        host_regex: '{{ .Values.host_regex }}'
        
        # Redirect when accessing the root URI
        root_uri: '/pun/sys/dashboard'
        
        # Sub-uri to reverse proxy to backend web server
        node_uri: '/node'
        
        # Sub-uri to reverse proxy to backend web server using only *relateive* URI paths
        rnode_uri: '/rnode'