apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-ondemand.fullname" . }}
  labels:
    {{- include "open-ondemand.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      name: http
    - port: 8080
      protocol: TCP
      name: kc8080
  selector:
    {{- include "open-ondemand.selectorLabels" . | nindent 4 }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "open-ondemand.fullname" . }}-ood
  labels:
    {{- include "open-ondemand.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: slate
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - {{ .Values.Instance }}.ondemand.{{ .Values.SLATE.Cluster.DNSName }}
    - {{ .Values.Instance }}.keycloak.{{ .Values.SLATE.Cluster.DNSName }}
    secretName: {{ .Values.Instance}}-open-ondemand
  rules:
  - host: {{ .Values.Instance }}.ondemand.{{ .Values.SLATE.Cluster.DNSName }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "open-ondemand.fullname" . }}
          servicePort: 80
  - host: {{ .Values.Instance }}.keycloak.{{ .Values.SLATE.Cluster.DNSName }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "open-ondemand.fullname" . }}
          servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-ondemand.fullname" . }}-cluster-ip
  labels:
    {{- include "open-ondemand.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: slate
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ports:
    - port: 22
  type: ClusterIP
  selector:
    {{- include "open-ondemand.selectorLabels" . | nindent 4 }}
