apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: faucet
  name: faucet
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: faucet
    spec:
      containers:
      - env:
        - name: FAUCET_CONFIG_STAT_RELOAD
        - name: FAUCET_EVENT_SOCK
        image: faucet/faucet:latest
        name: faucet
        ports:
        - containerPort: 6653
        - containerPort: 9302
        resources: {}
        volumeMounts:
        - mountPath: /var/log/faucet
          name: faucet-claim0
        - mountPath: /etc/faucet
          name: faucet-claim1
      restartPolicy: Always
      volumes:
      - name: faucet-claim0
        persistentVolumeClaim:
          claimName: faucet-claim0
      - name: faucet-claim1
        persistentVolumeClaim:
          claimName: faucet-claim1
status: {}
