apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: prometheus
  name: prometheus
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: prometheus
    spec:
      containers:
      - image: prom/prometheus:v2.6.1
        name: prometheus
        ports:
        - containerPort: 9090
        resources: {}
        volumeMounts:
        - mountPath: ~/faucet/prometheus
          name: prometheus-claim0
        - mountPath: ~/faucet/etc/prometheus/prometheus.yml
          name: prometheus-claim1
        - mountPath: ~/faucet/etc/prometheus/faucet.rules.yml
          name: prometheus-claim2
      restartPolicy: Always
      volumes:
      - name: prometheus-claim0
        persistentVolumeClaim:
          claimName: prometheus-claim0
      - name: prometheus-claim1
        persistentVolumeClaim:
          claimName: prometheus-claim1
      - name: prometheus-claim2
        persistentVolumeClaim:
          claimName: prometheus-claim2
status: {}
