# Instance to label use case of Frontier Squid deployment
# Generates app name as "condor-[Instance]"
# Enables unique instances of Frontier Squid in one namespace
Instance: global

CondorConfig:
  # The address of your HTCondor Central Manager
  CollectorHost: localhost
  # The name of the secret that was created for your HTCondor password file
  # This must be created *BEFORE* you instantiate the chart.
  PasswordFileSecret: condor-password 
  # The amount of memory (in MB) that Condor may use on the machine.
  MemoryLimit: 512
  # The number of CPUs that this condor instance may take advantage of.
  NumberCPUs: 1
  # The ID of the Node or cluster you are deploying on
  NodeID: SLATE-CONDOR
  # If there is a GPU available on the cluster, you can specify use of that
  # resource
  UseGPU: true
  # Only used if UseGPU is set to true
  NumberGPUs: 2
  # Path to scratch storage on the local node used by the HTCondor worker
  # If left commented, will use storage within the container
  # ExecuteDir: "/scratch/condor"

# The following is some extra configuration that we expose to users, but
# generally is not necessary to get an HTCondor worker node running. You might
# want to change things here if, for example, your security policies or ports
# differ from our assumptions.
CondorConfigFile: |-
  CCB_ADDRESS                         = $(COLLECTOR_HOST)
  START                               = TRUE
  SUSPEND                             = FALSE
  PREEMPT                             = FALSE
  KILL                                = FALSE
  DAEMON_LIST                         = MASTER, STARTD
  ALLOW_WRITE                         = condor_pool@*, submit-side@matchsession
  SEC_DEFAULT_AUTHENTICATION          = PREFERRED
  SEC_DEFAULT_ENCRYPTION              = OPTIONAL
  SEC_DEFAULT_INTEGRITY               = REQUIRED
  SEC_DEFAULT_AUTHENTICATION_METHODS  = PASSWORD
  SEC_PASSWORD_FILE                   = /etc/condor/condor_password
  ALLOW_ADMINISTRATOR                 = condor_pool@*/*
  USE_SHARED_PORT                     = TRUE
  SHARED_PORT_PORT                    = 0
  COLLECTOR_PORT                      = 9618
  PUBLISH_OBITUARIES                  = FALSE
  RUNBENCHMARKS                       = FALSE
  NUM_SLOTS                           = 1
  NUM_SLOTS_TYPE_1                    = 1
  SLOT_TYPE_1                         = cpus=100%
  SLOT_TYPE_1_PARTITIONABLE           = TRUE
