---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-servicex-app
  labels:
    instance: {{ .Values.Instance | quote }}
spec:
  ports:
   - port: 8000
     targetPort: 5000
     name: "tcp"
     protocol: TCP
  selector:
    app: {{ .Release.Name }}-servicex-app
  type: ClusterIP
