apiVersion: v1
kind: ConfigMap
metadata:
  name: condor-ce-{{ .Values.Instance }}-configuration
  labels:
    app: nginx
    instance: {{ .Values.Instance }}
data:
  hostcert.pem: |-
{{ .Values.Host.HostCertificate | indent 4 }}
  ssh_known_hosts: {{ .Values.RemoteHost.HostName }} {{ .Values.RemoteHost.HostKey }}
  # OSG config
  99-local.ini: |-
    [Site Information]
    group = OSG
    host_name = {{ .Values.CE.HostName }}
    resource =  {{ .Values.CE.SiteName }}
    resource_group = CHPC Group
    sponsor = osg:100
    site_policy = UNAVAILABLE
    contact = {{ .Values.CE.Contact }}
    email = {{ .Values.CE.Email }}
    city = {{ .Values.CE.City }}
    country = {{ .Values.CE.Country }}
    latitude = {{ .Values.CE.Latitude }}
    longitude = {{ .Values.CE.Longitude }}
    
    [BOSCO]
    enabled = True
    users = osg
    endpoint = {{ .Values.RemoteHost.User }}@{{ .Values.RemoteHost.HostName }}
    batch =  {{ .Values.RemoteHost.Batch }}
    ssh_key = /etc/osg/bosco.key
    max_jobs = {{ .Values.RemoteHost.MaxJobs }}
    
    [Misc Services]
    glexec_location = None
    edit_lcmaps_db = True
    authorization_method = vomsmap
    
    [Storage]
    se_available = False
    default_se = None
    grid_dir = /cvmfs/oasis.opensciencegrid.org/osg-software/osg-wn-client/current/el7-x86_64/
    app_dir = UNSET
    data_dir = None
    worker_node_temp = /scratch/
    site_read = None
    site_write = None
    
    [GIP]
    batch = condor
    advertise_gsiftp = False
    gsiftp_host = {{ .Values.CE.HostName }}
    advertise_gums = False
    
    [Subcluster]
{{ .Values.Cluster | indent 4 }}
    
    [SE_dummy]
    enabled = False
    name = dummy
    srm_endpoint =  srm://srm.example.com:8443/srm/v2/server
    provider_implementation  = bestman
    implementation  = bestman
    
    [Squid]
    enabled = {{ .Values.Proxy.Enabled }}
    location = {{ .Values.Proxy.Address }}
    policy = DEFAULT
    cache_size = DEFAULT
    memory_size = DEFAULT
  # gratia config
  ProbeConfig: |-
    <ProbeConfiguration
        Title1="Collector Information"
    
        CollectorHost="gratia-osg-prod.opensciencegrid.org:80"
        SSLHost="gratia-osg-prod.opensciencegrid.org:80"
        SSLRegistrationHost="gratia-osg-prod.opensciencegrid.org:80"
    
        CollectorService="/gratia-servlets/rmi"
        SSLCollectorService="/gratia-servlets/rmi"
        RegistrationService="/gratia-registration/register"
    
        Title2="Probe information and functional configuration"
    
        ProbeName="htcondor-ce:{{ .Values.CE.HostName }}"
        SiteName={{ .Values.CE.SiteName }}
        Grid="OSG"
        SuppressUnknownVORecords="0"
        SuppressNoDNRecords="0"
        SuppressGridLocalRecords="1"
        QuarantineUnknownVORecords="1"
        EnableProbe="1"
    
        Title3="Tuning parameter"
    
        BundleSize="100"
        MaxPendingFiles="100000"
        MaxStagedArchives="400"
        UseSyslog="0"
        ConnectionTimeout="900"
    
        LogLevel="2"
        Comments32="Controls debug messages printed to log file."
        DebugLevel="0"
        Comments33="Controls debug messages printed to screen."
        LogRotate="31"
        LogFileName=""
        Comments34="If LogFileName is set, then there is no log file rotation. Otherwise Log file rotation will create one new file each day and delete the older ones"
        DataLengthMax="0"
        Comments35="The maximum number of records (or hours, depending on the probe) processed in a single invocation, 0 = all records, no max"
        DataFileExpiration="31"
        Comments36="The number of days quarantined and unusable data files are kept"
        QuarantineSize="200"
        Comments37="The maximum size in Mb allowed to be kept in each quarantined directory"
        GratiaExtension="gratia.xml"
    
        Title4="Authentication Configuration"
    
        UseSSL="0"
        CertificateFile="/etc/grid-security/hostcert.pem"
        KeyFile="/etc/grid-security/hostkey.pem"
        UseGratiaCertificates="0"
        Comments40="If no directory is specified the gratia certificate file will be created in 'WorkingFolder'/certs."
        GratiaCertificateFile="/var/lib/gratia/data/certs/gratia.probecert.pem"
        GratiaKeyFile="/var/lib/gratia/data/certs/gratia.probekey.pem"
    
        Title5="File and directory location"
    
        UserVOMapFile="/var/lib/osg/user-vo-map"
        Comments51="Location and wildcard pattern of log files that contains certificate information about the jobs in the format followed by the 'blah demons'."
        CertInfoLogPattern="/var/log/accounting/blahp.log-*"
        CondorCEHistoryFolder="/var/lib/gratia/condorce_data"
    
        DataFolder="/var/lib/gratia/data/"
        WorkingFolder="/var/lib/gratia/tmp"
        LogFolder="/var/log/gratia"
    
        CondorScheddName=""
        Comments91="Use this to set the name of the scheduler, if there are mutliple."
        NoCertinfoBatchRecordsAreLocal="0"
    
        SOAPHost="gratia-osg-prod.opensciencegrid.org:80"
    />
  access-key: {{ .Values.PublicKey }}
