apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "condor-ce.fullname" . }}
  labels:
    app: {{ template "condor-ce.fullname" . }}
    chart: {{ template "condor-ce.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "condor-ce.fullname" . }}
      chart: {{ template "condor-ce.chart" . }}
      release: {{ .Release.Name }}
      instance: {{ .Values.Instance }}
  template:
    metadata:
      labels: 
        app: {{ template "condor-ce.fullname" . }}
        chart: {{ template "condor-ce.chart" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance }}
    spec:
      hostNetwork: true
      nodeSelector: 
        kubernetes.io/hostname: {{ .Values.NodeSelector }}
      containers:
      - name: condor-ce
        image: "slateci/container-condor-ce"
        imagePullPolicy: IfNotPresent
        ports:
        - name: ssh
          containerPort: 22
          protocol: TCP
        - name: collector
          containerPort: 9619
          protocol: TCP
        volumeMounts:
        - name: remote-host-key
          mountPath: "/etc/osg/bosco.key"
          subPath: bosco.key
        - name: condor-ce-{{ .Values.Instance }}-configuration
          mountPath: /etc/osg/config.d/99-local.ini
          subPath: 99-local.ini
        - name: condor-ce-{{ .Values.Instance }}-configuration
          mountPath: /tmp/ProbeConfig
          subPath: ProbeConfig
        - name: condor-ce-{{ .Values.Instance }}-configuration
          mountPath: /etc/ssh/ssh_known_hosts
          subPath: ssh_known_hosts
        - name: condor-ce-{{ .Values.Instance }}-configuration
          mountPath: /tmp/access-key
          subPath: access-key
        - name: grid-certs
          mountPath: /etc/grid-security/certificates
        - name: host-cert
          mountPath: /etc/grid-security/hostcert.pem
          subPath: hostcert.pem
        - name: host-key
          mountPath: /etc/grid-security/hostkey.pem
          subPath: hostkey.pem
      - name: fetchcrl
        image: edquist/fetchcrl-container
        volumeMounts:
        - name: grid-certs
          mountPath: /etc/grid-security/certificates
      initContainers:
      - name: fetchcrl
        image: edquist/fetchcrl-container
        command: ["/bin/sh"]
        args: ["-c", "osg-ca-manage setupCA --url osg; fetch-crl -p10 -T10"]
        volumeMounts:
        - name: grid-certs
          mountPath: /etc/grid-security/certificates
      volumes:
      - name: host-key
        secret:
          secretName: {{ .Values.Host.hostCertificateSecret }}
          items:
            - key: private_key
              path: hostkey.pem 
          defaultMode: 384
      - name: host-cert
        secret:
          secretName: {{ .Values.Host.hostCertificateSecret }}
          items:
            - key: cert
              path: hostcert.pem
      - name: remote-host-key
        secret:
          secretName: {{ .Values.RemoteHost.PrivateKeySecret }}
          items:
          - key: private_key
            path: bosco.key
      - name: condor-ce-{{ .Values.Instance }}-configuration
        configMap: 
          name: condor-ce-{{ .Values.Instance }}-configuration
      - name: grid-certs
        emptyDir: {}
      restartPolicy: Always
