apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nginx.fullname" . }}
  labels:
    app: {{ template "nginx.name" . }}
    chart: {{ template "nginx.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "nginx.name" . }}
      instance: {{ .Values.Instance | quote }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "nginx.name" . }}
        chart: {{ template "nginx.chart" . }}
        instance: {{ .Values.Instance | quote }}
        instanceID: {{ .Values.SLATE.Instance.ID | quote  }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: nginx
        image: "nginx:1.15.9"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: nginx-{{ .Values.Instance }}-configuration
          mountPath: /usr/share/nginx/html
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
      restartPolicy: Always
      volumes:
      - name: nginx-{{ .Values.Instance }}-configuration
        configMap:
          name: nginx-{{ .Values.Instance }}-configuration
