apiVersion: v1
name: xcache
# Chart version
version: 0.7.3
description: XCache is a xrootd based caching service for k8s
# Version of application packaged for installation
appVersion: "5.4.0"
home: http://slateci.io/XCache/
maintainers:
  - name: Ilija Vukotic
    email: ivukotic@uchicago.edu
