apiVersion: v1
name: xcache
# Chart version
version: 0.5.9.1
description: XCache is a xrootd based caching service for k8s
# Version of application packaged for installation
appVersion: "5.1.0 rc6"
home: http://slateci.io/XCache/
maintainers:
  - name: Ilija Vukotic
    email: ivukotic@uchicago.edu
