apiVersion: v1
kind: Service
metadata:
  name: {{ template "osg-hosted-ce.fullname" . }}
  labels:
    app: {{ template "osg-hosted-ce.name" . }}
    chart: {{ template "osg-hosted-ce.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: "Local"
  ports:
  - name: htcondor-ce
    port: 9619
    protocol: TCP
  - name: http
    port: 80
    protocol: TCP
  {{ if .Values.HTTPLogger.Enabled }}
  - name: logs
    port: 8080
    protocol: TCP
  {{ end }}
  {{ if .Values.Networking.RequestIP }}
  loadBalancerIP: {{ .Values.Networking.RequestIP }}
  {{ end }}
  selector:
    app: {{ template "osg-hosted-ce.name" . }}
    instance: {{ .Values.Instance }}
