apiVersion: v1
kind: Service
metadata:
  name: {{ template "grafana.fullname" . }}
  labels:
    app: {{ template "grafana.name" . }}
    chart: {{ template "grafana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.Service.labels }}
{{ toYaml .Values.Service.labels | indent 4 }}
{{- end }}
{{- with .Values.Service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.Service.ExternalVisibility }}
  {{ if ne .Values.Service.ExternalVisibility "ClusterIP" }}
  externalTrafficPolicy: Local
  {{ end }}
  ports:
    - name: service
      port: {{ .Values.Service.Port }}
      protocol: TCP
      targetPort: 3000
  selector:
    app: {{ template "grafana.name" . }}
    release: {{ .Release.Name }}
