apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "v4a.fullname" . }}
data:
  default.vcl: |-
    vcl 4.1;
    import dynamic;
    import directors;

    {{- range $nindex, $be := .Values.backends }}
    backend {{ $be.name }} {
        .host = "{{ $be.host }}";
        .port = "{{ $be.port }}";
    }
    {{- end }}

    acl local {
    {{.Values.acl | nindent 4 }}
    }

    sub vcl_init {
        new vdir = directors.round_robin();
        {{- range $nindex, $be := .Values.backends }}
        vdir.add_backend({{ $be.name }});
        {{- end }}  
    }

    sub vcl_recv {
        set req.backend_hint = vdir.backend();        
        set req.http.X-frontier-id = "varnish";
        if (client.ip !~ local) {
            return (synth(405));
        } 
        if (req.method != "GET" && req.method != "HEAD") {
            return (pipe);
        }

    }

