# The label to apply to this deployment, 
# used to manage multiple instances of the same application
Instance: ''

# Persistent Volume mounted as 'data' in the user's home directory
PersistentVolume: 

# Ingress control settings  
Ingress:
  # The subdomain to associate with this service.
  # This will result in a FQDN like {subdomain}.{cluster}.slateci.net
  Subdomain: 'jupyter'
  # The class of the ingress controller to use. 
  # For SLATE this should be 'slate'. 
  Class: slate
Jupyter:
  #Change this if you want to have a custom username and home directory
  NB_USER: 'jovyan'
  #Change this if you want to have a custom unix UID, 
  #for example, to match one you use on a shared filesystem
  NB_UID: 1000
  #Change this if you want to have a custom default unix GID, 
  #for example, to match one you use on a shared filesystem
  NB_GID: 100
  #If you change NB_GID you should set this to the name you want your 
  #custom group to have. This must be different from any existing group name
  NB_GROUP: my-group
  #The below hashed password can only be generated using a Jupyter function called "notebook.auth.security.passwd()" So you don't have access to another Jupyter setup to use that function, you should probably leave the Sample default value. (It doesn't correspond to a real password)  
  Password: 'sha1:94491e2a6996:9024SampleHashedPassword5cf4276925cb6b151'
  #Generate a random token for authentication and add it below
  Token: '90246f039b038==RandomlyGenerated==cf4276925cb6b151'
Resources:
  # The maximum amount of CPU resources the notebook should be able to use
  # in units of thousandths of a CPU core, e.g. 1000 == 1 CPU core. 
  CPU: 1000
  # The maximum amount of memory the notebook should be able to use, 
  # in megabytes. 
  # Note that jupyter and other built-in components use some memory,
  # so somewhat less than the value specified here will be available 
  # to user code. 
  Memory: 256
  # Enable CVMFS
  Cvmfs: false
  # GPU: 1

CondorConfig:
  #Change this to true and set the other variables in this section 
  #to enable the notebook to submit batch jobs to an HTCondor pool
  Enabled: false
  #Add the IP address for the condor collector
  CollectorHost: 127.0.0.1
  #Add the port number for the condor collector
  CollectorPort: 30287
  # The port on which the condor components in this deployment should listen. 
  # If your Central manager is within the same Kubernetes cluster, the default
  # value of 9618 will work. Otherwise, you must guess an unused port within 
  # the Kubernetes cluster's NodePort range. This range is usually, but not
  # always 30000-32767
  ExternalCondorPort: 9618
  # This boolean variable needs to be set to true if this chart will be used to 
  # submit jobs to the OSG central manager. If the intention is to use the chart
  # with a local condor pool installed on SLATE, it needs to be set to false. In
  # either case, this configuration will only take effect if the CondorConfig>Enabled
  # is set to true.
  IsExternalPool: false
  # This is the name used for the password from which the token for the collector 
  # host was created. It is a good idea to make sure that this does not match the 
  # name of any password which is present on the collector host
  KeyName: jupyter
  # This must be the name used for the issuer of the token for the collector host.
  # It should be different from CollectorHost. 
  TrustDomain: jupyter
  # The name of a secret which contains the authentication data needed by this
  # submit host. It must contain two keys:
  # - condor_token: A token issued by the central manager
  # - reverse_password: The passwrd used to issue a token to the central manager 
  #                     on behalf of this submit host
  AuthTokenSecret: submit-auth-token
SSH:
  #Change this to true and set a public key below to enable direct 
  #login to the notebook container with SSH
  Enabled: false
  #Do NOT use your SSH private key here. Your public ssh key starts with 'ssh-rsa'
  SSH_Public_Key: 'ssh-rsa AAAAB3N=====SamplePublicSSHKey======vH6Edp6+J81Itt+x8Cy/JrjMhzSjAs5Gt1RiKdMSmhclGz3s+h/KL8f12tjA3Uk0PSPqgRTN2L435/X1Hche7CiT6ZJqpCoxa8J4mbLzYaLeGWnNremJ90Q/udO+IUYvviDsgDeB1msIDWfIylDxMteMZ50WTkPVur+Yl2TG6mxNNdNshzHSxtOM3IB2+Q9ChYRFB59J38Wx1+9/1Mnf53 slate'

# Enable this section if you have additional middleware that needs to have an
# open inbound tcp port to function.
ExtraPort:
  Enabled: false
  LowPort:  31000
  HighPort: 31002

### SLATE-START ###
SLATE:
  Cluster:
    DNSName: 'some-cluster.slateci.net'
### SLATE-END ###
