Site: "MWT2"
varnish_size: "32G"
varnish_container_port: 80

nodeSelector:
  varnish: frontier-slate

acl: |-
  "localhost";
  "72.36.96.0"/24; 
  "149.165.224.0"/23; 
  "192.170.240.0"/23;

backends:
  # atlasfrontier1-ai.cern.ch
  - name: backend20
    host: 188.184.29.207
    port: 8000
  - name: backend21
    host: 2001:1458:201:e5::100:c1
    port: 8000
    # atlasfrontier2-ai.cern.ch
  - name: backend30
    host: 188.184.29.104
    port: 8000
  - name: backend31
    host: 2001:1458:201:e5::100:5a
    port: 8000

resources:
  requests:
    cpu: "4"
    memory: "33Gi"
  limits:
    cpu: "48"
    memory: "48Gi"

### SLATE-START ###
Instance: slate01
SLATE:
  Instance:
    ID: "untagged"
### SLATE-END ###
